# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SonglinkCli < Formula
  desc "Paste an URL from any music service. The app will generate a song.link URL and copy it to your clipboard automatically"
  homepage "https://github.com/marcusziade/songlink-cli-homebrew"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/marcusziade/songlink-cli/releases/download/v0.0.1/songlink-cli_0.0.1_Darwin_arm64.tar.gz"
      sha256 "fb303f504488bbd3ba15acb1066e0c99c6b96a5332931114c4b815b05207edda"

      def install
        bin.install "songlink-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/marcusziade/songlink-cli/releases/download/v0.0.1/songlink-cli_0.0.1_Darwin_x86_64.tar.gz"
      sha256 "02245c3c2bc97cc4d2df2e26229eeb97711f57917262bd08134f2192d679c159"

      def install
        bin.install "songlink-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/marcusziade/songlink-cli/releases/download/v0.0.1/songlink-cli_0.0.1_Linux_arm64.tar.gz"
      sha256 "ce62c14ab066ca1c3d91d08108f42c81594ef94628b7c170d1c2c98644f65a8e"

      def install
        bin.install "songlink-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/marcusziade/songlink-cli/releases/download/v0.0.1/songlink-cli_0.0.1_Linux_x86_64.tar.gz"
      sha256 "433b23630756665214b491484b8ea8f9e13c981437dd505484eff200d86aac14"

      def install
        bin.install "songlink-cli"
      end
    end
  end
end
