# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SonglinkCli < Formula
  desc "Paste an URL from any music service. The app will generate a song.link URL and copy it to your clipboard automatically"
  homepage "https://github.com/marcusziade/homebrew-songlink-cli"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/marcusziade/songlink-cli/releases/download/v0.0.2/songlink-cli_0.0.2_Darwin_arm64.tar.gz"
      sha256 "5eafb800ebc7ecd2688e481944f3b84c584db6d60c66b47aef504773445dfefb"

      def install
        bin.install "songlink-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/marcusziade/songlink-cli/releases/download/v0.0.2/songlink-cli_0.0.2_Darwin_x86_64.tar.gz"
      sha256 "726c16e01c5c84ad09bcd4d403b79f5ec2367d3d301c4c5dfe0eecc1b18d914d"

      def install
        bin.install "songlink-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/marcusziade/songlink-cli/releases/download/v0.0.2/songlink-cli_0.0.2_Linux_arm64.tar.gz"
      sha256 "a7fc62d8993115ea24f8fe39a9743aefc709bb4e8df3b324cb0270a0e3431fdd"

      def install
        bin.install "songlink-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/marcusziade/songlink-cli/releases/download/v0.0.2/songlink-cli_0.0.2_Linux_x86_64.tar.gz"
      sha256 "9b288812f0e0a538b8a0f4b347cc15105736a0e95cf882177fce0d2ef180abeb"

      def install
        bin.install "songlink-cli"
      end
    end
  end
end
